### ISSUE TITLE
Will the code be released?

### ISSUE THREAD

**Issue by Thaison03** [StonyBrookNLP/ircot#1]
As title.

**Comment by HarshTrivedi** [comment]
For sure! I'm hoping to release the camera-ready code in 1-1.5 months. Am quite a bit bogged down by other things at the moment. Meanwhile if you have any specific issues, shoot me an email I'll try best to help you out.

**Comment by ezekielbarnett** [comment]
bump

**Comment by shahules786** [comment]
How's it difficult to release the code if you have done such experiments? If you're waiting to perfect it, something is better than nothing.

**Comment by HarshTrivedi** [comment]
I've been working on preparing the camera-ready code [here](https://github.com/HarshTrivedi/ircot-cameraready-prep). It's pretty much done at this point. I'm just rerunning some more experiments as sanity checks which may take 1-2 more days. If anyone's interested feel free to check it out. I'll be moving that codebase to this repository after the sanity checks are finished.

**Comment by HarshTrivedi** [comment]
The code has been released now. Check out the readme.
