### ISSUE TITLE
When indexing, Elasticsearch instance fails to connect to localhost

### ISSUE THREAD

**Issue by kerkathy** [StonyBrookNLP/ircot#11]
Hi,

Thank you for your awesome work and your kindness to share the code. I really love the idea of querying database using LLM generation response. It's very inspiring! :)

However, when I followed `README.md` I seem to have a little trouble with elasticsearch since it's my first time using it and I'm kinda confused about everything. 
I successfully started elasticsearch server on port 9200, and the retriever server at port 8000, but stuck at indexing. When I run `python retriever_server/build_index.py hotpotqa` until this line 
```
    es.indices.create(index=elasticsearch_index, ignore=400, body=paragraphs_index_settings)
```

It first shows the error
```
Traceback (most recent call last):                                                                                                        
  File "/home/guest/r11944026/anaconda3/envs/ircot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 791, in urlopen           
    response = self._make_request(                                                                                                        
  File "/home/guest/r11944026/anaconda3/envs/ircot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 537, in _make_request     
    response = conn.getresponse()                                                                                                         
  File "/home/guest/r11944026/anaconda3/envs/ircot/lib/python3.8/site-packages/urllib3/connection.py", line 461, in getresponse           
    httplib_response = super().getresponse()                                                                                              
  File "/home/guest/r11944026/anaconda3/envs/ircot/lib/python3.8/http/client.py", line 1322, in getresponse                               
    response.begin()                                                                                                                      
  File "/home/guest/r11944026/anaconda3/envs/ircot/lib/python3.8/http/client.py", line 303, in begin                                      
    version, status, reason = self._read_status()                                                                                         
  File "/home/guest/r11944026/anaconda3/envs/ircot/lib/python3.8/http/client.py", line 272, in _read_status                               
    raise RemoteDisconnected("Remote end closed connection without"                                                                       
http.client.RemoteDisconnected: Remote end closed connection without response    
During handling of the above exception, another exception occurred:                                                                       
...
```
and there're more errors left behind.

At the same time, the elasticsearch server log shows
```
[2023-10-24T15:14:41,827][WARN ][o.e.h.n.Netty4HttpServerTransport] [cuda8] received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/127.0.0.1:9200, remoteAddress=/127.0.0.1:50652}
```

It seems to be a HTTP vs HTTPs problem. Therefore I tried brutely changing this line in `build_index.py`
```
    elastic_host = "localhost"
```
to 
```
    elastic_host = "https://localhost"
```
but it still doesn't work.

Could you please give me a hand? I'll really appreciate it.

Note: I notice that I followed official installation guide and I'm using elastic search 8.10, which is different from your version. Could that possibly be the reason?

**Comment by canghongjian** [comment]
I have just started indexing.
<img width="556" alt="image" src="https://github.com/StonyBrookNLP/ircot/assets/34473193/ad293fc3-fc68-42c4-a9c2-1d2e33bdce55">

Maybe you should check whether your elasticsearch server on port 9200 ran successfully.

**Comment by kerkathy** [comment]
@canghongjian  Thanks a lot! (btw I have also read your beam retrieval paper and I like the idea 😆)


Maybe that's the problem... actually the situation is I'm running elasticsearch on a remote server.
While I'm able to access `https://<remote_server_ip>:9200/` via edge browser on my local computer and all the information are shown (cluster name, cluster uuid, ...) ,
I receive an empty reply if I `curl localhost:9200` or `curl https://<remote_server_ip>:9200/` directly on command line on my server.


I tried to add `network.host: 0.0.0.0` in `elasticsearch.yml` but sadly nothing works.

**Comment by canghongjian** [comment]
Haha, thanks for your interest. In fact I also ran elasticsearch server and retriever server on a remote server, and then I started the indexing script. I follow the README exactly and the `elasticsearch==7.9.1`. Maybe you can try it again in the same environment as possible.
