### ISSUE TITLE
Ongoing Maintenance and Setup Queries for ircot Project

### ISSUE THREAD

**Issue by hippoley** [StonyBrookNLP/ircot#15]
Hey Harsh Trivedi,

I've been trying to get my local setup aligned with the ` ircot` project, specifically the state of the repo at this commit: `8637316e5e94ba0a2493e5df7846f2f23f46eaef`. 

I'm running into a few hiccups trying to replicate the environment on my end. Just wondering if there have been any updates to the `requirements.txt` or any particular package versions that I should use for a smooth setup?

Thanks a lot for your help, and for all the awesome work you're putting out there!

Cheers,
Hippoley

**Comment by HarshTrivedi** [comment]
Thanks for your comments! There hasn't been any change to the requirements.txt since the first commit. However since most requirements are not pinned, an updated version of a certain requirement may be causing a problem. Might be able to help if you can post your error stack trace.
