### ISSUE TITLE
How much does it cost to solve this problem

### ISSUE THREAD

**Issue by Fu-Dayuan** [StonyBrookNLP/ircot#2]
for GPT3 I wonder about the cost of money and the cost of time in 4 dataset
for flan-T5 I wonder about the cost of time in 4 datasets with different size
can you provide the actual data?

**Comment by Fu-Dayuan** [comment]
Hi, I sent an email to hjtrivedi@cs.stonybrook.edu. Did you receive it?

**Comment by HarshTrivedi** [comment]
I think this has been long resolved. I am closing it now. Feel free to open it again if there is a follow-up.
