### ISSUE TITLE
Query about the origin of hp_manager package

### ISSUE THREAD

**Issue by XLMcmath** [StonyBrookNLP/ircot#25]
![image](https://github.com/StonyBrookNLP/ircot/assets/32157555/6b4724f1-0678-4fe8-9eac-4a46bdd5ab06)

Hello,

I am currently working with project. I check the requirements.txt but there's no clue about the "hp_manager". I was wondering where it from and if there is any documentation or information available about its origin. Could you please provide some details or point me to the right resources?

Thank you for your time and assistance.

**Comment by HarshTrivedi** [comment]
Sorry for the late response. Looks like it's a remnant of the old non-camera-ready code. I have fixed the import in [here](https://github.com/StonyBrookNLP/ircot/commit/8585d7438efea28e7a79e3f08ff15e4c307135d9).

**Comment by XLMcmath** [comment]
oh that's the same function in run.py , thx that helps.
