### ISSUE TITLE
How to get the chain of thoughts annotations from the original data

### ISSUE THREAD

**Issue by jarheadjoe** [StonyBrookNLP/ircot#3]
![image](https://user-images.githubusercontent.com/21330284/226869220-c1af459e-4a7f-4def-b222-4c3054bb0c52.png)

**Comment by HarshTrivedi** [comment]
Hi @jarheadjoe, I'm not sure what the question is. These CoT annotations were manually written. They are already there in the paper pdf. If you want full prompt files, shoot me an email and I'll be happy to share them with you.

**Comment by jarheadjoe** [comment]
> Hi @jarheadjoe, I'm not sure what the question is. These CoT annotations were manually written. They are already there in the paper pdf. If you want full prompt files, shoot me an email and I'll be happy to share them with you.

I see, thanks for the reply. I'll go write the email now.

**Comment by jarheadjoe** [comment]
> 

Did you get my email(591428779@qq.com)?

**Comment by jarheadjoe** [comment]
@HarshTrivedi Did you get my email (591428779@qq.com)? Please check my letter in case it is in the trash

**Comment by HarshTrivedi** [comment]
Hi! Yeah, I received your email. I have been traveling for last 3 days. I will have access to internet and laptop tomorrow. I will get back then. Sorry for the delay.
