### ISSUE TITLE
Question about the figure demonstration

### ISSUE THREAD

**Issue by helloeve** [StonyBrookNLP/ircot#7]
Hi, thank you for the great work! I have a question for the figure demonstration in this repo (Figure 2 in the paper). The right hand side "Reason" step takes in the triplet of (Q, yellow documents retrieved by the Q, T1). However, if I understand your approach correctly, the input should actually be (Q, yellow documents retrieved by the Q and `blue documents retrieved by the T1`, T1)?

**Comment by HarshTrivedi** [comment]
You are correct! The Reason step section was mainly to give a sense of the prompt for the next "thought" generation. But I see that color coding in it is misleading. It should have had both yellow and blue docs. Thanks for the catch!
