### ISSUE TITLE
`2wikimultihopqa` Raw Data

### ISSUE THREAD

**Issue by lyy1994** [StonyBrookNLP/ircot#8]
Hi Harsh, the `download/raw_data.sh` script does not download (or extract?) the raw data of `2wikimultihopqa` correctly, as I found an empty folder in `raw_data/2wikimultihopqa`. Could you please update the script? Thanks!

**Comment by HarshTrivedi** [comment]
Thanks for reporting! It's fixed now. For some reason, the exact wget command worked when I ran it from the terminal, but not when I ran it from the bash script. Removing the file_subpath did the trick. It should work now.
